### ISSUE TITLE
dpm8600 question

### ISSUE THREAD

**Issue by kthemall** [d4rken/jt-dpm8600-psu-mqtt#1]
hi, Matthias!

can you explain a bit what exactly your code does? i also am just trying to code in python a script which sets the current of the dpm8624 individually to what i get from my amis-reader (likely the volkszaehler).

i have a json file which i got but how do you handle the problem with your code? 

i´m a bit of new in the microcontroller area so please if you want to support me? 

i can flash an esp but i do not exactly know how to bring your code onto the esp. 

thx tom (german language)

**Comment by d4rken** [comment]
> can you explain a bit what exactly your code does? i also am just trying to code in python a script which sets the current of the dpm8624 individually to what i get from my amis-reader (likely the volkszaehler).

Write its current status to a MQTT broker, and read values from the same broker to use as new settings (on/off, current limit, voltage limit).

![Screenshot from 2023-01-06 07-47-54](https://user-images.githubusercontent.com/1439229/210946071-9ef86473-e93a-4431-8c09-73fe14364731.png)

I also have a Tasmota/Volkszähler.
I'm connecting all of this in NodeRed and constantly calculating new limits for the DPM so that I only provide as much power as needed to an inverter, as any excess would be gifted to the local utilities provider.

> i have a json file which i got but how do you handle the problem with your code?

This code "connects" the DPM via an Arduino to my wifi and allows me to remotely configure it via MQTT.

> i´m a bit of new in the microcontroller area so please if you want to support me?
> i can flash an esp but i do not exactly know how to bring your code onto the esp.

* Rename `Config.h.sample` to `Config.h` enter your wifi and mqtt broker data
* Open the project with VSCode + PlatformIO and flash it to your Arduino
* Now the DPM data should appear in your broker and it should also listen to the `command` values in that same broker (see screenshot above)

If you don't have an MQTT broker running somewhere yet, you need to host one on a Raspberry Pi or Arduino in your WiFi.

**Comment by kthemall** [comment]
thx so far. i will give it a try and let you knowbest wishestom

**Comment by kthemall** [comment]
hi, just to be sure, my last question: do you use dpm with ttl or with rs485 controller?

 

 

i think your code is based on a git project that works only for ttl version of the dpm??

 

thx tom

 

 
 

Gesendet: Freitag, 06. Januar 2023 um 07:58 Uhr
Von: "Matthias Urhahn" ***@***.***>
An: "d4rken/jt-dpm8600-psu-mqtt" ***@***.***>
Cc: "kthemall" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [d4rken/jt-dpm8600-psu-mqtt] dpm8600 question (Issue #1)


 


can you explain a bit what exactly your code does? i also am just trying to code in python a script which sets the current of the dpm8624 individually to what i get from my amis-reader (likely the volkszaehler).


Write its current status to a MQTT broker, and read values from the same broker to use as new settings (on/off, current limit, voltage limit).



I also have a Tasmota/Volkszähler.
I'm connecting all of this in NodeRed and constantly calculating new limits for the DPM so that I only provide as much power as needed to an inverter, as any excess would be gifted to the local utilities provider.


i have a json file which i got but how do you handle the problem with your code?


This code "connects" the DPM via an Arduino to my wifi and allows me to remotely configure it via MQTT.


i´m a bit of new in the microcontroller area so please if you want to support me?
i can flash an esp but i do not exactly know how to bring your code onto the esp.



	Rename Config.h.sample to Config.h enter your wifi and mqtt broker data
	Open the project with VSCode + PlatformIO and flash it to your Arduino
	Now the DPM data should appear in your broker and it should also listen to the command values in that same broker (see screenshot above)


If you don't have an MQTT broker running somewhere yet, you need to host one on a Raspberry Pi or Arduino in your WiFi.

**Comment by d4rken** [comment]
Please stop responding via email or fix your email program. It totally mangles the text and just spams a huge block of text.

I don't have access to it to check the specific version, but I think it's the RS485 version. 

I'm using this adapter between the arduino and the DPM module:
https://www.amazon.de/gp/product/B09VGJCJKQ

The TTL version has a blue connector and the RS485 has a green one? Mine is green.

> i think your code is based on a git project that works only for ttl version of the dpm??

It does seem to work :shrug:.
